### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by burntcookie90** [burntcookie90/shoe#1]
```
e: [ksp] java.lang.ClassCastException: class java.util.Collections$SingletonMap cannot be cast to class java.util.LinkedHashMap (java.util.Collections$SingletonMap and java.util.LinkedHashMap are in module java.base of loader 'bootstrap')
	at com.vishnurajeevan.shoe.ShoeProcessor$ShoeVisitor.visitFunctionDeclaration(ShoeProcessor.kt:88)
	at com.vishnurajeevan.shoe.ShoeProcessor$ShoeVisitor.visitFunctionDeclaration(ShoeProcessor.kt:55)
```

**Comment by burntcookie90** [comment]
fixed 09836a9f17a5604ca5a5fa3c3f4f755510e5152a
